name: variant
description: A variant generator for FLutter applications.
version:  0.1.0-alpha
homepage: https://github.com/aloisdeniel/variant

environment:
  sdk: '>=2.18.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
